apiVersion: v2
name: wave-planning-service
description: Intelligent wave planning with multi-strategy optimization
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
- paklog
- warehouse
- wms
- microservices
maintainers:
- name: Paklog Team
